pillow: Depends on Python for Linuxbrew
Fix libImaging/ImPlatform.h:10:20: fatal error:
Python.h: No such file or directory

Closes #5443.

Signed-off-by: Shaun Jackman <sjackman@gmail.com>