salmon 0.6.0
Depends on xz for lzma.h
cram_io.c:66:10: fatal error: 'lzma.h' file not found

Closes #3407.

Signed-off-by: Shaun Jackman <sjackman@gmail.com>