ckon: bump revision for boost and fix test
- attempting to run the test would throw

  dyld: Symbol not found: __ZN5boost9re_detail12perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE14construct_initERKNS_11basic_regexIcSD_EENS_15regex_constants12_match_flagsE
    Referenced from: /usr/local/Cellar/ckon/0.7.1/bin/ckon
      Expected in: /usr/local/lib/libboost_regex-mt.dylib
       in /usr/local/Cellar/ckon/0.7.1/bin/ckon

  so ckon needs a new revision built against the latest boost.

- once rebuilt, the test was still slightly broken due to changes in the
  tested repository, so fix that, and peg the test to a specific commit
  revision of tschaume/BesCocktail

Closes #3467.

Signed-off-by: Dominique Orban <dominique.orban@gmail.com>