kent-tools: Fix DSO missing from command line
Fix the error on Linuxbrew:
jkweb.a(zlibFace.o): undefined reference to symbol 'uncompress'
libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status